# Surfpool.toml
# Basic configuration for testing keeper code with stake pool, validator history, and steward programs

[network]
# Set slot time (in ms) - faster for quicker testing
slot_time = 1

# Your mainnet RPC endpoint - replace with your preferred RPC
rpc_url = "https://api.mainnet-beta.solana.com"

# Network binding
host = "127.0.0.1"
port = 8899

[deployment]
# Disable auto-deployment if you're only testing with mainnet programs
auto_deploy = false

[airdrop]
# Pre-fund your keeper wallet and test accounts
addresses = [
    "BgKUXdS29YcHCFrPm5M8oLHiTzZaMDjsebggjoaQ6KFL"
]
amount = 0.00001  # 10,000 SOL in lamports

# Alternative: fund from keypair file
keypair_paths = [
    "~/.config/solana/id.json",
]

[programs]
# The programs you need for testing
# Surfpool will automatically fetch these and their accounts on-demand
validator_history = "HistoryJTGbKQD2mRgLZ3XhqHnN811Qpez8X9kCcGHoa"
steward = "Stewardf95sJbmtcZsyagb2dg4Mo8eVQho8gpECvLx8"

[ui]
# Enable the explorer UI for debugging
enable_explorer = true

# Enable TUI for better visibility
enable_tui = true
